JamesBrill/react-speech-recognition

README.md, src/SpeechRecognition.js
The goal of this PR is to give the user more control over the Web Speech API. Previously, the recognition object was not aborting speech recognition detection correctly, and was failing on re-renders. The use of a singleton recognition object and improved controls should alleviate this issue.
* `listening` bool prop: if true, the Web Speech API is listening to speech from the microphone.
* `startListening` func prop: causes the Web Speech API to start listening to speech from the microphone.
* `stopListening` func prop: causes the Web Speech API to stop listening to speech from the microphone, but will finish processing any remaining speech.
* `abortListening` func prop: causes the Web Speech API to stop listening to speech from the microphone, and also stop processing the current speech. …
=> Better recognition control

README.md, src/SpeechRecognition.js
You can configure the default initial state of the Speech Recognition API. To change these defaults, you need to pass an options object into the wrapper like so:
```
const options = {
autoStart: false
}
export default SpeechRecognition(options)(YourComponent)
```
or in ES7:
`@SpeechRecognition(options)`
By default, the Speech Recognition API is listening to speech from the microphone. To have the API turned off by default, set this to `false`.
=> Configurable default state

.babelrc, package.json, src/SpeechRecognition.js
- Stop depending on `core-decorators`.
- If rendered on the server, don't fail when trying to access `window`.
=> Enable server side rendering

README.md, src/SpeechRecognition.js
I've added the new option to enable users to control the API. Using a new option property, users can enable/disable the continuous listening of the API. I kept the default configs to be continuous and made the necessary modifications that will add the feature.
=> New option to disable continuous listening

src/SpeechRecognition.js
it tries to set values on a null recognition reference in lines 31 onwards (constructor)
added a check to ensure it's not null
=> fix: graceful exit in safari

src/SpeechRecognition.js, src/utils.js
On Android, there are two strange behaviours as documented [here](https://stackoverflow.com/questions/35112561/speech-recognition-api-duplicated-phrases-on-android/43458449#43458449):
- Interim transcripts are marked as "final" with confidence 0
- Final transcripts are often emitted twice
This PR handles this by doing the following:
- Treating "final" transcripts with confidence 0 as interim transcripts on Android
- Debouncing final transcripts on Android, waiting 250ms between each one
=> Collect final transcripts correctly in Android

README.md, package-lock.json, package.json
Install was broken due to the postinstall referencing the `example` folder in this repo, which is not published to npm.
=> Fix postinstall

README.md, example/src/Dictaphone/DictaphoneWidgetA.js, package-lock.json, package.json, src/SpeechRecognition.js, src/SpeechRecognition.test.js
Command callbacks do not have access to the `resetTranscript` function as they have to be defined before `resetTranscript` is returned by `useSpeechRecognition`. This PR addresses this problem by passing `resetTranscript` to the command callbacks as the last argument. This is put inside an object to allow further properties to be passed in future. Intended to address https://github.com/JamesBrill/react-speech-recognition/issues/53
=> Reset transcript in command callback

package-lock.json, package.json, src/isAndroid.js, src/isAndroid.test.js
Adds fallback for server-side rendering when `navigator` is not defined. Is the release of https://github.com/JamesBrill/react-speech-recognition/pull/61
=> Fix SSR support

package-lock.json, package.json, src/SpeechRecognition.js
Because the `commands` prop is an array, its value is always deemed to be changing when either (a) the default value is used or (b) the consumer does not memoize their `commands` value. The various callbacks and effects depending on `commands` get re-run on every change, including unrelated changes (e.g. transcript).
This was resulting in a race condition when multiple instances of `SpeechRecognition` were being rendered. While the transcript was being updated, the new transcripts would cause `commands` to "change" and re-run the dependent effects, including the one that subscribes and unsubscribes `SpeechRecognition` to `RecognitionManager`. As `RecognitionManager` updates its subscribers of transcript changes, they unsubscribe and resubscribe with a different ID. When having to iterate …
=> Make commands mutable

docs/API.md, package-lock.json, package.json, src/RecognitionManager.js, src/SpeechRecognition.js
`stopListening` and `abortListening` were previously synchronous functions, but the internal function for turning off the microphone is asynchronous. This made it impossible for consumers to wait for the microphone to be turned off. This PR addresses that, making these functions asynchronous and wait for the microphone to be turned off before returning.
=> Async stopListening

README.md, example/src/Dictaphone/DictaphoneWidgetA.js, package-lock.json, package.json, src/SpeechRecognition.js, src/SpeechRecognition.test.js
Based on https://github.com/JamesBrill/react-speech-recognition/issues/70, this enables an array of "phrases" to be passed into a command, allowing one callback to be triggered by multiple commands. e.g.
```
{
command: ['Hello', 'Hi'],
callback: () => setMessage('Hi there'),
matchInterim: true
}
```
=> Array-based commands

package-lock.json, package.json
To enable consumers that provide an array of command phrases for the same command callback, the lib now passes in the matched command phrase back to the callback. This is passed in through the last argument as the `command` property. Example:
```
{
command: ['Hello', 'Hi'],
callback: ({ command }) => setMessage(`Hi there! You said: "${command}"`),
matchInterim: true
}
```
=> Identify command that triggered callback

README.md, example/src/Dictaphone/DictaphoneWidgetA.js, package-lock.json, package.json, src/SpeechRecognition.js, src/SpeechRecognition.test.js
When an array of command phrases is provided for a fuzzy command, there is the possibility that the callback will be triggered multiple times. For example, take the following command:
```
{
command: ['eat', 'sleep', 'leave'],
callback: (command) => console.log(command),
isFuzzyMatch: true,
fuzzyMatchingThreshold: 0.2
}
```
If the user says "leap", the callback will be triggered three times as it matches all three command phrases.
This release introduces a new command option `bestMatchOnly`. This is `false` by default but when set will ensure the callback is only called _once_ by the command phrase with the best match. If we modify the example above to
```
{
command: ['eat', 'sleep', 'leave'],
callback: (command) => console.log(command),
isFuzzyMatch: true,
fuzzyMatchingThreshold: 0.2, …
```
=> bestMatchOnly option for fuzzy matching

README.md, docs/API.md, docs/POLYFILLS.md, example/src/Dictaphone/Dictaphone.js, example/src/Dictaphones.js, package-lock.json, package.json, src/RecognitionManager.js, src/SpeechRecognition.js, src/SpeechRecognition.test.js, tests/vendor/corti.js
The first support for polyfill integration! Highly experimental stuff. Allows for the Speech Recognition engine to be switched out for a polyfill. Tested with an Azure polyfill with the integration documented.
If you want `react-speech-recognition` to work on more browsers than just Chrome, you can integrate a polyfill. This is a piece of code that fills in some missing feature in browsers that don't support it.
Under the hood, Web Speech API in Chrome uses Google's speech recognition servers. To replicate this functionality elsewhere, you will need to host your own speech recognition service and implement the Web Speech API using that service. That implementation, which is essentially a polyfill, can then be plugged into `react-speech-recognition`. You can write that polyfill yourself, …
=> Support polyfills

README.md, docs/API.md, package-lock.json, package.json, src/RecognitionManager.js, src/SpeechRecognition.js, src/android.test.js
Allow users of continuous listening to disable the feature on browsers that don't support it by listening for a new `browserSupportsContinuousListening` state emitted from `useSpeechRecognition`.
Also added a Troubleshooting section to the README regarding Regenerator Runtime.
=> Flag for continuous listening support

README.md, docs/API.md, docs/POLYFILLS.md, example/src/Dictaphone/Dictaphone.js, package-lock.json, package.json, src/RecognitionManager.js, src/SpeechRecognition.js, src/SpeechRecognition.test.js
When `react-speech-recognition` first starts to listen, the browser will usually ask the user whether they give permission for the microphone to be used. If they deny access, `react-speech-recognition` did not previously handle this well:
* For native browser implementations of the Web Speech API, it would be unaware that permission hadn't been given and indicate to consumers that the microphone was listening
* For polyfills that throw errors when attempting to start listening in such a case, the error was not being caught, resulting in consumer apps crashing
This PR introduces a new state: `isMicrophoneAvailable`. If the user denies access to the microphone, the value of this will change to `false`. This applies in both of the following cases:
* On-spec case: where the recognition object …
=> Microphone availability detection

docs/API.md, docs/POLYFILLS.md, example/src/Dictaphones.js, package-lock.json, package.json, src/SpeechRecognition.js, src/SpeechRecognition.test.js
If a polyfill was applied using `applyPolyfill`, reset the Speech Recognition engine to the native implementation. This can be useful when the user switches to a language that is supported by the native engine but not the polyfill engine.
```
SpeechRecognition.removePolyfill()
```
Inspired by https://github.com/JamesBrill/react-speech-recognition/issues/145
=> removePolyfill function

README.md, docs/POLYFILLS.md
Removes setup instructions for Speechly; speechly.com is defunct and the polyfill has been archived.
Closes #191
Closes #182
Closes #160
Closes #150 
Closes #143
=> docs: remove Speechly instructions

package.json, src/RecognitionManager.js, src/utils.js, yarn.lock
I picked the irrelevant change from #247.
=> Replace custom `debounce` function with `lodash.debounce`
